name: Test Action

on:
    push:
        branches: [main, master]
    workflow_dispatch:

permissions:
    id-token: write
    contents: write

jobs:
    test-audit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6
              with:
                  fetch-depth: 0
            - name: Run Local Action
              uses: ./
              with:
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  logAnalyticsWorkspaceId: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
                  daysToQuery: 7
                  enableGitCommit: "true"
            - name: Verify Outputs
              shell: pwsh
              run: |
                  if (Test-Path ".lpm-audit/inventory.json") {
                      Write-Host "Success!"
                  } else {
                      throw "Audit file missing"
                  }
